export class AsyncMessager {

    private nameToPrint: string;

    private supperArray: string[];

    constructor(nameToPrint: string) {
        this.nameToPrint = nameToPrint;
        this.supperArray = [
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",   "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
               "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",   "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",     "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst", "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
            "tessssst",
        ];
    }

    public getSuperArray(): string[] {
        return this.supperArray;
    }

    public getAsyncMessage(messageToPrint: string): Promise<string> {
        return new Promise((resolve, reject) => {
            resolve(`This is an async message to: ${this.nameToPrint} - ${messageToPrint}`);
        });
    }

}
